# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.7"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache pip install
      uses: actions/cache@v3
      id: cache-venv
      with:
        path: ./.venv/
        key: ${{ runner.os }}-${{ matrix.python-version}}-venv-1a-${{ hashFiles('requirements.txt') }}
        restore-keys: ${{ runner.os }}-${{ matrix.python-version}}-venv-1a-
    - name: Build virtual environment with dependencies
      if: steps.cache-venv.outputs.cache-hit != 'true'
      run: |
        mkdir -p ./.venv
        python -m venv ./.venv
        . ./.venv/bin/activate
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # - name: Run typechecker on library
    #   run: |
    #     . ./.venv/bin/activate
    #     make typecheck_library
    - name: Run library unit tests
      run: |
        . ./.venv/bin/activate
        env PYTHONPATH=. make unittest_library
    - name: Run examples
      run: |
        . ./.venv/bin/activate
        env PYTHONPATH=. make test_examples
